version: '3'

services:
  api:
    build: .
    ports:
      - '8081:8081'
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: db_urlshortener
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'email@email.com'
      PGADMIN_DEFAULT_PASSWORD: '#postgres2021#'
    ports:
      - '16543:80'
    depends_on:
      - db
    networks:
      - postgres-compose-network

volumes:
  database-data: #Volume for persist data when container shuts down

networks:
  postgres-compose-network:
    driver: bridge
